# Generated by Django 4.2 on 2024-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_productbrand_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان در url'),
        ),
    ]
