# Generated by Django 4.2 on 2024-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_productcategory_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان در url'),
        ),
    ]
