# Generated by Django 4.2 on 2024-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productcategory_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان در url'),
        ),
    ]
