# Generated by Django 4.2 on 2023-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=100, verbose_name=' دامنه سایت')),
                ('about_us_text', models.TextField(max_length=100, verbose_name='متن درباره ما')),
                ('is_main_setting', models.BooleanField(max_length=100, verbose_name='تنظیمات اصلی')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فکس')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('copy_right', models.TextField(max_length=100, verbose_name='متن کپی رایت')),
                ('site_logo', models.ImageField(upload_to='images/site_setting', verbose_name='لوگو سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
