# Generated by Django 4.2 on 2023-08-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_slider_url_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='بنر')),
                ('image', models.ImageField(upload_to='images/bannetrs', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(max_length=200, verbose_name='فعال/غیرفعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه بنر محصولات'), ('product_detail', 'صفحه جزییات محصولات'), ('about_us', 'صفحه درباره ما محصولات')], max_length=200, verbose_name='جایگاه نمایش')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
