# Generated by Django 4.2 on 2024-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(upload_to='images/banners', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزییات محصولات'), ('about_us', 'صفحه درباره ما محصولات')], max_length=200, verbose_name='جایگاه نمایش'),
        ),
    ]
