# Generated by Django 4.2 on 2023-08-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLinkBox',
        ),
    ]
