# Generated by Django 4.2 on 2023-08-15 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 8, 15), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
