# Generated by Django 4.2 on 2024-03-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='Article',
            new_name='article',
        ),
    ]
